name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [6, 8, 10]
    
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/hello
      with: 
        who-to-greet: ${{ matrix.tag }}
    - name: configure
      run: ls 
